Prevent accidental view input after triggering document symbols
sublimelsp/LSP pull request #1326
Opened 2020-09-15 18:46 UTC by rchl

After triggering LSP's "Document Symbols", the user might start typing
the query immediately and if the server response is delayed the query
would end up changing the view. This is a stop-gap solution to avoid
such accidental input until https://github.com/sublimehq/sublime_text/issues/3338
is implemented.

Resolves #1323

2020-09-15 18:58 UTC, rwols requested changes

2020-09-15 18:58 UTC, rwols commented on plugin/symbols.py
> +        self.view.settings().erase('lsp_supress_input')
Also log the error to the status bar, like the default error handler does.

2020-09-15 18:58 UTC, rwols commented on plugin/symbols.py
> +        self.view.settings().erase('lsp_supress_input')
Hmm... `handle_response` runs in some thread somewhere. That means that theoretically what could happen is: the view setting is erased, then the user types a character, and only then the quickpanel is shown.

In order to guarantee atomicity here, we should run the handler on the UI thread with `sublime.set_timeout`.

2020-09-15 18:58 UTC, rwols commented on plugin/symbols.py
> +        self.view.settings().set('lsp_supress_input', True)
Typo: supress -> suppress

2020-09-15 18:58 UTC, rwols commented on Keymaps/Default (Linux).sublime-keymap
> +        ],
It feels dangerous, but let's try it anyway. Note that things like backspace and the enter key are not handled by `<character>`. But I think there's a low chance that anyone is pressing those keys.

2020-09-16 19:34 UTC, rwols commented
I'll merge this after a release because I'm still afraid that that `<character>` binding will break something.

2020-09-16 19:37 UTC, rchl commented
No problem. The scope the key-binding is enabled is very narrow but we can play it safe in case it works in an unexpected way.

2020-09-16 19:57 UTC, merged