Add information about LSP-pylsp
sublimelsp/LSP pull request #1691
Opened 2021-05-27 21:52 UTC by rchl

2021-05-27 21:53 UTC, rchl commented
Not sure if too drastic to remove `pyls` client configuration...

2021-05-27 22:35 UTC, rwols requested changes

2021-05-27 22:35 UTC, rwols commented on LSP.sublime-settings
> -    },
Let's deprecate it first in the release message and remove it after release.

2021-05-28 20:39 UTC, rwols approved these changes

2021-05-28 20:40 UTC, merged