Add Godot (GDScript) LSP instructions
sublimelsp/LSP pull request #2001
Opened 2022-07-23 00:40 UTC by lucypero

2022-07-24 18:16 UTC, rwols requested changes
Thanks! I have a minor formatting nitpick.

2022-07-24 18:16 UTC, rwols commented on docs/src/language_servers.md
> +```
This code block should be indented by 4 spaces to make it a part of the bullet point.

2022-07-24 19:23 UTC, lucypero commented
> Thanks! I have a minor formatting nitpick.

Done

2022-07-24 19:32 UTC, rwols approved these changes

2022-07-24 19:32 UTC, merged

2022-07-24 19:40 UTC, rwols commented
Wouldn't this also require a step to install some Godot scripting language syntax?

2022-07-24 20:00 UTC, lucypero commented
> Wouldn't this also require a step to install some Godot scripting language syntax?

Yes, you need to install the GDScript plugin to get syntax highlighting.

2022-07-24 21:11 UTC, rwols commented
Would it be possible for you to add that as “step 1” in the instructions? Other instructions mention that as well, if the syntax is not shipped with ST.

2022-07-25 22:58 UTC, lucypero commented
> Would it be possible for you to add that as “step 1” in the instructions? Other instructions mention that as well, if the syntax is not shipped with ST.

https://github.com/sublimelsp/LSP/pull/2005